services:
    marello_return.shipping.integration.service_data_provider:
        class: Marello\Bundle\ReturnBundle\Provider\ReturnShippingServiceDataProvider
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: marello.shipping.data_provider,  class: %marello_return.entity.return.class% }
