navigation:
    menu_config:
        items:
            packingSlips:
                label: 'marello.packing.packingslip.entity_plural_label'
                route: 'marello_packing_packingslip_index'
                extras:
                    routes: ['marello_packing_packingslip_*']
                    position: 20

        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            packingSlips: ~

    titles:
        marello_packing_packingslip_index:  'marello.packing.packingslip.entity_plural_label'
        marello_packing_packingslip_view:   'Packing Slip #%id%'
