placeholders:
    items:
        marello_inventory_log_chart_item:
            action:     MarelloInventoryBundle:InventoryLog:chart
            applicable: true

    placeholders:
        marello_inventory_log_chart:
            items:
                marello_inventory_log_chart_item: ~
