acls:
    marello_order_create:
        type: entity
        class: MarelloOrderBundle:Order
        permission: CREATE

    marello_order_view:
        type: entity
        class: MarelloOrderBundle:Order
        permission: VIEW

    marello_order_update:
        type: entity
        class: MarelloOrderBundle:Order
        permission: EDIT

    marello_customer_view:
        type: entity
        class: MarelloOrderBundle:Customer
        permission: VIEW

    marello_customer_create:
        type: entity
        class: MarelloOrderBundle:Customer
        permission: CREATE

    marello_customer_update:
        type: entity
        class: MarelloOrderBundle:Customer
        permission: EDIT
