Marello\Bundle\InventoryBundle\Entity\Warehouse:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [code]
            errorPath: code
            message: 'marello.inventory.validation.messages.error.unique_warehouse_code'
    properties:
        label:
            - NotBlank: ~
        code:
            - NotBlank: ~

Marello\Bundle\InventoryBundle\Entity\WarehouseGroup:
    properties:
        name:
            - NotBlank: ~
        warehouses:
            - NotBlank: ~

Marello\Bundle\InventoryBundle\Entity\WarehouseChannelGroupLink:
    properties:
        warehouseGroup:
            - NotBlank: ~
        salesChannelGroups:
            - Valid: ~
            - Count:
                min: 1
                minMessage: 'marello.inventory.validation.messages.error.warehousechannelgrouplink.has_no_channel_groups'

Marello\Bundle\InventoryBundle\Entity\InventoryItem:
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\GreaterThanOrEqualToValue:
            fields: [desiredInventory, purchaseInventory]
            errorPath: desiredInventory
            message: 'marello.inventory.validation.messages.error.inventoryitem.desired_should_be_greater_than_purchase_inventory'