acls:
    marello_refund_create:
        type: entity
        class: MarelloRefundBundle:Refund
        permission: CREATE

    marello_refund_view:
        type: entity
        class: MarelloRefundBundle:Refund
        permission: VIEW

    marello_refund_update:
        type: entity
        class: MarelloRefundBundle:Refund
        permission: EDIT
