navigation:
    menu_config:
        items:
            refunds:
                label: marello.refund.entity_plural_label
                route: marello_refund_index
                extras:
                    routes: ['marello_refund_*']
                    position: 40


        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            refunds: ~

    titles:
        marello_refund_index: marello.refund.entity_plural_label
