#
# Marello config
#
fos_js_routing:
    routes_to_expose:         [marello_*]

oro_help:
    defaults:
        link: 'http://www.marello.com/'
        server: http://www.marello.com/
        prefix: Third_Party
    vendors:
        Marello:
            prefix: ~
            alias: Marello

oro_theme:
    active_theme: oro
    themes:
        oro:
            icon: bundles/marellolayout/images/marello.ico

oro_sidebar:
    sidebar_widgets:
        sticky_note:
            icon: "bundles/marellolayout/images/marello.ico"
            settings:
                content: |
                    Welcome to Marello!
                    Marello is an easy-to-use, open source ERP for your ecommerce business. learn more at www.marello.com
oro_ui:
    settings:
        organization_name:
            value:            "Marello"