acls:
    marello_return_view:
        type:       entity
        class:      MarelloReturnBundle:ReturnEntity
        permission: VIEW

    marello_return_create:
        type:       entity
        class:      MarelloReturnBundle:ReturnEntity
        permission: CREATE

    marello_return_update:
        type:       entity
        class:      MarelloReturnBundle:ReturnEntity
        permission: EDIT
