datagrids:
    marello-return:
        source:
            type: orm
            query:
                select:
                    - r
                    - COALESCE(SUM(ri.quantity), 0) AS returnItemCount
                    - (SELECT SUM(oi.quantity) FROM MarelloOrderBundle:OrderItem oi WHERE oi.order = r.order ) AS orderItemCount
                from:
                    - { table: MarelloReturnBundle:ReturnEntity, alias: r }
                join:
                    left:
                        - { join: r.returnItems, alias: ri }
                        - { join: r.order, alias: o }
                groupBy: r.id, o.id
        columns:
            returnNumber:
                data_name: returnnumber
                label: marello.return.returnentity.return_number.label
                frontend_type: string
            orderNumber:
                data_name: order.orderNumber
                label: marello.order.order_number.label
                type: twig
                frontend_type: html
                template: MarelloOrderBundle:Order:Datagrid/Property/orderNumber.html.twig
            returnItems:
                data_name: returnItemCount
                label: marello.return.returnitem.returned_quantity.label
                frontend_type: number
            orderItems:
                data_name: orderItemCount
                label: marello.return.returnitem.ordered_quantity.label
                frontend_type: number
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        filters:
            columns:
                returnNumber:
                    type: string
                    data_name: r.returnNumber
                orderNumber:
                    type: string
                    data_name: o.orderNumber
                createdAt:
                    type: datetime
                    data_name: r.createdAt
                updatedAt:
                    type: datetime
                    data_name: r.updatedAt
        sorters:
            columns:
                returnNumber:
                    data_name: r.returnNumber
                orderNumber:
                    data_name: o.orderNumber
                returnItems:
                    data_name: returnItemCount
                createdAt:
                    data_name: r.createdAt
                updatedAt:
                    data_name: r.updatedAt
            default:
                returnNumber: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        properties:
            view_link:
                type:   url
                route:  marello_return_return_view
                params:
                    id: id
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye
                rowAction:  true

    marello-return-customer:
        source:
            type: orm
            query:
                select:
                    - r
                    - COALESCE(SUM(ri.quantity), 0) AS returnItemCount
                    - (SELECT SUM(oi.quantity) FROM MarelloOrderBundle:OrderItem oi WHERE oi.order = r.order ) AS orderItemCount
                from:
                    - { table: MarelloReturnBundle:ReturnEntity, alias: r }
                join:
                    left:
                        - { join: r.returnItems, alias: ri }
                        - { join: r.order, alias: o }
                groupBy: r.id, o.id
                where:
                    and:
                        - o.customer = :customer_id
            bind_parameters:
                customer_id: customerId
        columns:
            returnNumber:
                data_name: returnnumber
                label: marello.return.returnentity.return_number.label
                frontend_type: string
            orderNumber:
                data_name: order.orderNumber
                label: marello.order.order_number.label
                type: twig
                frontend_type: html
                template: MarelloOrderBundle:Order:Datagrid/Property/orderNumber.html.twig
            returnItems:
                data_name: returnItemCount
                label: marello.return.returnitem.returned_quantity.label
                frontend_type: number
            orderItems:
                data_name: orderItemCount
                label: marello.return.returnitem.ordered_quantity.label
                frontend_type: number
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        filters:
            columns:
                returnNumber:
                    type: string
                    data_name: r.returnNumber
                orderNumber:
                    type: string
                    data_name: o.orderNumber
                createdAt:
                    type: datetime
                    data_name: r.createdAt
                updatedAt:
                    type: datetime
                    data_name: r.updatedAt
        sorters:
            columns:
                returnNumber:
                    data_name: r.returnNumber
                orderNumber:
                    data_name: o.orderNumber
                returnItems:
                    data_name: returnItemCount
                createdAt:
                    data_name: r.createdAt
                updatedAt:
                    data_name: r.updatedAt
            default:
                returnNumber: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        properties:
            view_link:
                type:   url
                route:  marello_return_return_view
                params:
                    id: id
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye
                rowAction:  true
        options:
            export: false
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    marello-return-items:
        source:
            type: orm
            query:
                select:
                    - ri
                from:
                    - { table: MarelloReturnBundle:ReturnItem, alias: ri }
                join:
                    left:
                        - { join: ri.orderItem, alias: oi }
                where:
                    and:
                        - ri.return = :return_id
            bind_parameters:
                return_id: returnId
        columns:
            sku:
                data_name: orderItem.productSku
                label: marello.product.sku.label
                frontend_type: string
            product:
                data_name: orderItem.productName
                label: marello.product.name.label
                frontend_type: string
            quantityOrdered:
                data_name: orderItem.quantity
                label: marello.order.orderitem.quantity.label
                frontend_type: number
            quantityReturned:
                data_name: quantity
                label: marello.return.returnitem.returned_quantity.label
                frontend_type: number
            status:
                data_name: status
                label: marello.return.returnitem.status.label
                frontend_type: string
            reason:
                data_name: reason
                label: marello.return.returnitem.reason.label
                frontend_type: string
            rowTotal:
                data_name:        orderItem.rowTotalInclTax
                label:            marello.order.orderitem.total_price_incl_tax.label
                type:             localized_number
                method:           formatCurrency
                context_resolver: Marello\Bundle\DataGridBundle\Grid\FormatterContextResolver::getRootResolverCurrencyClosure
                align:            right
