processes:
    definitions:
        marello_return_apply_business_rules:
            label:   'Apply Return Business Rules'
            enabled: true
            entity:  Marello\Bundle\ReturnBundle\Entity\ReturnEntity
            order:   10
            exclude_definitions: [marello_return_apply_business_rules]
            actions_configuration:
                - '@tree':
    #                conditions:
    #                    @and:
    #                        - @gt: []
                    actions:
                        - '@call_service_method':
                            attribute: $.businessRuleManager
                            service: 'marello_return.manager.businessrule_manager'
                            method: 'applyRules'
                            method_parameters: [$.data]
    triggers:
        marello_return_apply_business_rules:
            -
                event:    create
                priority: 5
                queued:   true