services:
    marello_supplier.form.type.supplier:
        class: Marello\Bundle\SupplierBundle\Form\Type\SupplierType
        tags:
            - { name: form.type, alias: marello_supplier_form }

    marello_supplier.form.type.supplier_select:
        class: Marello\Bundle\SupplierBundle\Form\Type\SupplierSelectType
        tags:
            - { name: form.type, alias: marello_supplier_select_form }

    ## forms
    marello_supplier.supplier.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'marello_supplier_form'
            - 'marello_supplier_form'

    ## handlers
    marello_supplier.form.handler.supplier:
        class: Marello\Bundle\SupplierBundle\Form\Handler\SupplierHandler
        scope: request
        arguments:
            - '@marello_supplier.supplier.form'
            - '@request'
            - '@doctrine.orm.entity_manager'

    marello_supplier.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%marello_supplier.supplier.entity.class%'
            - "@doctrine.orm.entity_manager"