marello_tax_taxcode:
    resource: "@MarelloTaxBundle/Controller/TaxCodeController.php"
    type:     annotation
    prefix:   /marello/tax/taxcode

marello_tax_taxjurisdiction:
    resource: "@MarelloTaxBundle/Controller/TaxJurisdictionController.php"
    type:     annotation
    prefix:   /marello/tax/taxjurisdiction

marello_tax_taxrate:
    resource: "@MarelloTaxBundle/Controller/TaxRateController.php"
    type:     annotation
    prefix:   /marello/tax/taxrate

marello_tax_taxrule:
    resource: "@MarelloTaxBundle/Controller/TaxRuleController.php"
    type:     annotation
    prefix:   /marello/tax/taxrule
