search:
    Marello\Bundle\TaxBundle\Entity\TaxCode:
        alias:                          marello_taxcodes
        title_fields:                   [code]
        route:
            name:                       marello_tax_taxcode_index
            parameters:
                id:                     id
        search_template: MarelloTaxBundle:TaxCode:searchResult.html.twig
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]

    Marello\Bundle\TaxBundle\Entity\TaxRate:
        alias:                          marello_taxrates
        title_fields:                   [code]
        route:
            name:                       marello_tax_taxrate_view
            parameters:
                id:                     id
        search_template:                MarelloTaxBundle:TaxRate:searchResult.html.twig
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]

    Marello\Bundle\TaxBundle\Entity\TaxJurisdiction:
        alias:                          marello_taxjurisdiction
        title_fields:                   [code]
        route:
            name:                       marello_tax_taxjurisdiction_view
            parameters:
                id:                     id
        search_template:                MarelloTaxBundle:TaxJurisdiction:searchResult.html.twig
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]
