services:
    marello_orocommerce.form.type.orocommerce_settings:
        class: 'Marello\Bundle\OroCommerceBundle\Form\Type\OroCommerceSettingsType'
        arguments:
            - '@marello_orocommerce.cache'
            - '@marello_orocommerce.cache_key_generator'
            - '@oro_locale.settings'
        tags:
            - { name: form.type }

    marello_orocommerce.form.extension.channel_connectors:
        class: 'Marello\Bundle\OroCommerceBundle\Form\Extension\ChannelConnectorsExtension'
        tags:
            - { name: form.type_extension, extended_type: 'Oro\Bundle\IntegrationBundle\Form\Type\ChannelType' }

    marello_orocommerce.sync_state:
        class: 'Marello\Bundle\OroCommerceBundle\Model\SyncState'
        arguments:
            - '@doctrine'
            - '@logger'

    marello_orocommerce.cache:
        parent: oro.cache.abstract
        calls:
            - [setNamespace, ['marello_orocommerce']]

    marello_orocommerce.cache_key_generator:
        class: 'Marello\Bundle\OroCommerceBundle\Generator\CacheKeyGenerator'

    marello_orocommerce.rest.client_factory:
        public: true
        class: 'Marello\Bundle\OroCommerceBundle\Client\Factory\OroCommerceRestClientFactory'

    marello_orocommerce.event_listener.doctrine.saleschannelgroup_integration_check_listener:
        class: 'Marello\Bundle\OroCommerceBundle\EventListener\Doctrine\SalesChannelGroupIntegrationCheckListener'
        arguments:
            - '@session'
        lazy:  true
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Marello\Bundle\SalesBundle\Entity\SalesChannelGroup', event: preRemove }

    marello_orocommerce.event_listener.doctrine.update_integration_saleschannels_listener:
        class: 'Marello\Bundle\OroCommerceBundle\EventListener\Doctrine\UpdateIntegrationSalesChannelsListener'
        lazy:  true
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    marello_orocommerce.revers_sync_integration_processor:
        class: 'Marello\Bundle\OroCommerceBundle\Async\OroCommerceReversSyncIntegrationProcessor'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_integration.reverse_sync.processor'
            - '@oro_integration.manager.types_registry'
            - '@oro_message_queue.job.runner'
            - '@security.token_storage'
            - '@logger'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    marello_orocommerce.integration.channel:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\OroCommerceChannelType'
        public: true
        tags:
            - { name: oro_integration.channel, type: orocommerce }

    marello_orocommerce.integration.transport:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Transport\Rest\OroCommerceRestTransport'
        public: true
        calls:
            - [setRestClientFactory, ['@marello_orocommerce.rest.client_factory']]
        tags:
            - { name: oro_integration.transport, type: orocommerce, channel_type: orocommerce }

    marello_orocommerce.integration.connector.abstract:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\AbstractOroCommerceConnector'
        abstract: true
        arguments:
          - '@marello_orocommerce.sync_state'
          - '@oro_importexport.context_registry'
          - '@oro_integration.logger.strategy'
          - '@oro_integration.provider.connector_context_mediator'

    marello_orocommerce.integration.connector.customer:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceCustomerConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: customer, channel_type: orocommerce }

    marello_orocommerce.integration.connector.paymentterm:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommercePaymentTermConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: payment_term, channel_type: orocommerce }

    marello_orocommerce.integration.connector.product:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceProductConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: product, channel_type: orocommerce }

    marello_orocommerce.integration.connector.product_price:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceProductPriceConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: product_price, channel_type: orocommerce }

    marello_orocommerce.integration.connector.product_image:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceProductImageConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: product_image, channel_type: orocommerce }

    marello_orocommerce.integration.connector.inventory_level:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceInventoryLevelConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: inventory_level, channel_type: orocommerce }

    marello_orocommerce.integration.connector.tax_code:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceTaxCodeConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: tax_code, channel_type: orocommerce }

    marello_orocommerce.integration.connector.tax_rate:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceTaxRateConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: tax_rate, channel_type: orocommerce }

    marello_orocommerce.integration.connector.tax_jurisdiction:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceTaxJurisdictionConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: tax_jurisdiction, channel_type: orocommerce }

    marello_orocommerce.integration.connector.tax_rule:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceTaxRuleConnector'
        public: false
        parent: marello_orocommerce.integration.connector.abstract
        tags:
            - { name: oro_integration.connector, type: tax_rule, channel_type: orocommerce }

    marello_orocommerce.integration.connector.order:
        class: 'Marello\Bundle\OroCommerceBundle\Integration\Connector\OroCommerceOrderConnector'
        public: false
        arguments:
          - '@marello_orocommerce.sync_state'
          - '@oro_importexport.context_registry'
          - '@oro_integration.logger.strategy'
          - '@oro_integration.provider.connector_context_mediator'
        tags:
            - { name: oro_integration.connector, type: order, channel_type: orocommerce }

    marello_orocommerce.validator.warehouse_exists_for_enterprise_edition:
        class: 'Marello\Bundle\OroCommerceBundle\Validator\WarehouseExistsForEnterpriseEditionValidator'
        tags:
            - { name: validator.constraint_validator, alias: 'marello_orocommerce.warehouse_exists_for_enterprise_edition_validator' }