services:
    marello_order.workflow.order_ship_action:
        class: 'Marello\Bundle\OrderBundle\Workflow\OrderShipAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
            - '@event_dispatcher'
            - '@marello_inventory.provider.order_warehouse'
        tags:
            - { name: oro_action.action, alias: marello_ship_order }

    marello_order.workflow.order_cancel_action:
        class: 'Marello\Bundle\OrderBundle\Workflow\OrderCancelAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
            - '@event_dispatcher'
        tags:
            - { name: oro_action.action, alias: marello_cancel_order }

    marello_order.workflow.order_pick_pack_action:
        class: 'Marello\Bundle\OrderBundle\Workflow\OrderPickAndPackAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
            - '@event_dispatcher'
            - '@marello_inventory.provider.order_warehouse'
        tags:
            - { name: oro_action.action, alias: marello_pick_pack_order }
