navigation:
    menu_config:
        items:
            marello_categories:
                label: marello.catalog.category.entity_plural_label
                route: marello_category_index
                extras:
                    routes: ['marello_category_*']
                    position: 20
        tree:
            application_menu:
                children:
                    products_tab:
                        children:
                            marello_categories: ~

    titles:
        marello_category_index: 'marello.catalog.category.entity_plural_label'
        marello_category_create: 'New Category'
        marello_category_view: '%name%'
        marello_category_update: '%name%'
