api:
    entity_aliases:
        Marello\Bundle\ServicePointBundle\Entity\Facility:
            alias: marellofacility
            plural_alias: marellofacilities
        Marello\Bundle\ServicePointBundle\Entity\ServicePoint:
            alias: marelloservicepoint
            plural_alias: marelloservicepoints
        Marello\Bundle\ServicePointBundle\Entity\ServicePointAddress:
            alias: marelloservicepointaddress
            plural_alias: marelloservicepointaddresses
        Marello\Bundle\ServicePointBundle\Entity\ServicePointFacility:
            alias: marelloservicepointfacility
            plural_alias: marelloservicepointfacilities
        Marello\Bundle\ServicePointBundle\Entity\BusinessHours:
            alias: marellobusinesshours
            plural_alias: marellobusinesshours
        Marello\Bundle\ServicePointBundle\Entity\TimePeriod:
            alias: marellotimeperiod
            plural_alias: marellotimeperiods
        Marello\Bundle\ServicePointBundle\Entity\BusinessHoursOverride:
            alias: marellobusinesshoursoverride
            plural_alias: marellobusinesshoursoverrides
        Marello\Bundle\ServicePointBundle\Entity\TimePeriodOverride:
            alias: marellotimeperiodoverride
            plural_alias: marellotimeperiodoverrides

    entities:
        Marello\Bundle\ServicePointBundle\Entity\Facility:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: false
        Marello\Bundle\ServicePointBundle\Entity\ServicePoint:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: false
        Marello\Bundle\ServicePointBundle\Entity\ServicePointAddress:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: true
        Marello\Bundle\ServicePointBundle\Entity\ServicePointFacility:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: false
        Marello\Bundle\ServicePointBundle\Entity\BusinessHours:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: true
        Marello\Bundle\ServicePointBundle\Entity\TimePeriod:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: true
        Marello\Bundle\ServicePointBundle\Entity\BusinessHoursOverride:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: true
        Marello\Bundle\ServicePointBundle\Entity\TimePeriodOverride:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: true
