security:
    acl:
        connection: default
        cache:
            id: security.acl.cache.doctrine
            prefix: sf2_acl_

    firewalls:
        main:
            pattern: ^%web_backend_prefix%/
            organization-http-basic:
                realm: "Secured REST Area"
            provider: oro_user
            http-basic: false
            organization-form-login: false
            logout: false
            organization-remember-me: false
            anonymous: true

        frontend:
            pattern: ^/
            organization-http-basic:
                realm: "AccountUser REST Area"
            provider: commerce_customer_user
            context: customer_identity
            http-basic: false
            organization-form-login: false
            logout: false
            organization-remember-me: false
            anonymous_customer_user: true
